name: Matthew Hayward Murray
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.49144921265542507
  saturation: 0.30799303483217955
  rhythmicContrast: 0.9176697996445
purpose: []
